apiVersion: superset.apache.org/v1alpha1
kind: SupersetCeleryBeat
metadata:
  labels:
    app.kubernetes.io/name: superset
    app.kubernetes.io/component: celery-beat
    app.kubernetes.io/instance: superset-sample
  name: superset-sample
spec:
  image:
    tag: "latest"
    pullPolicy: IfNotPresent
  replicas: 1
  config: |
    import os
  configChecksum: "sha256:example..."
