#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Render the supported-Kubernetes-versions block from .github/supported-k8s.json
# into README.md and the docs, between sentinel comments:
#
#   <!-- BEGIN SUPPORTED-K8S -->
#   ... generated block ...
#   <!-- END SUPPORTED-K8S -->

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="${REPO_ROOT}/.github/supported-k8s.json"
TARGETS=(
  "${REPO_ROOT}/README.md"
  "${REPO_ROOT}/docs/index.md"
  "${REPO_ROOT}/docs/user-guide/installation.md"
)

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

supported="$(jq -r '[.supported[].minor] | join(", ")' "${SOURCE}")"
next="$(jq -r '.next.minor // empty' "${SOURCE}")"

block="$({
  echo '<!-- BEGIN SUPPORTED-K8S -->'
  echo '<!-- generated by `make supported-versions`; do not edit -->'
  echo "- **Officially tested:** Kubernetes ${supported}"
  if [ -n "${next}" ]; then
    echo "- **Experimental (best-effort):** Kubernetes ${next}"
  fi
  echo '<!-- END SUPPORTED-K8S -->'
})"

for file in "${TARGETS[@]}"; do
  if ! grep -q '<!-- BEGIN SUPPORTED-K8S -->' "${file}"; then
    echo "no sentinel block found in ${file}" >&2
    exit 1
  fi
  tmp="$(mktemp)"
  BLOCK="${block}" awk '
    /<!-- BEGIN SUPPORTED-K8S -->/ {
      print ENVIRON["BLOCK"]
      skip = 1
      next
    }
    /<!-- END SUPPORTED-K8S -->/ {
      skip = 0
      next
    }
    !skip { print }
  ' "${file}" > "${tmp}"
  mv "${tmp}" "${file}"
done
